class UpDistrict {
  final String hindiName;
  final String englishName;

  const UpDistrict({required this.hindiName, required this.englishName});
}

class UpDistrictsRegistry {
  static const List<UpDistrict> allDistricts = [
    UpDistrict(hindiName: 'लखनऊ', englishName: 'Lucknow'),
    UpDistrict(hindiName: 'कानपुर नगर', englishName: 'Kanpur Nagar'),
    UpDistrict(hindiName: 'कानपुर देहात', englishName: 'Kanpur Dehat'),
    UpDistrict(hindiName: 'प्रयागराज (इलाहाबाद)', englishName: 'Prayagraj'),
    UpDistrict(hindiName: 'वाराणसी', englishName: 'Varanasi'),
    UpDistrict(hindiName: 'गोरखपुर', englishName: 'Gorakhpur'),
    UpDistrict(hindiName: 'आगरा', englishName: 'Agra'),
    UpDistrict(hindiName: 'मेरठ', englishName: 'Meerut'),
    UpDistrict(hindiName: 'गाजियाबाद', englishName: 'Ghaziabad'),
    UpDistrict(hindiName: 'गौतम बुद्ध नगर (नोएडा)', englishName: 'Gautam Buddha Nagar'),
    UpDistrict(hindiName: 'अलीगढ़', englishName: 'Aligarh'),
    UpDistrict(hindiName: 'बरेली', englishName: 'Bareilly'),
    UpDistrict(hindiName: 'मुरादाबाद', englishName: 'Moradabad'),
    UpDistrict(hindiName: 'सहारनपुर', englishName: 'Saharanpur'),
    UpDistrict(hindiName: 'अयोध्या (फैजाबाद)', englishName: 'Ayodhya'),
    UpDistrict(hindiName: 'झांसी', englishName: 'Jhansi'),
    UpDistrict(hindiName: 'मथुरा', englishName: 'Mathura'),
    UpDistrict(hindiName: 'मुजफ्फरनगर', englishName: 'Muzaffarnagar'),
    UpDistrict(hindiName: 'आजमगढ़', englishName: 'Azamgarh'),
    UpDistrict(hindiName: 'बस्ती', englishName: 'Basti'),
    UpDistrict(hindiName: 'शाहजहांपुर', englishName: 'Shahjahanpur'),
    UpDistrict(hindiName: 'फिरोजाबाद', englishName: 'Firozabad'),
    UpDistrict(hindiName: 'मिर्जापुर', englishName: 'Mirzapur'),
    UpDistrict(hindiName: 'सुलतानपुर', englishName: 'Sultanpur'),
    UpDistrict(hindiName: 'रायबरेली', englishName: 'Raebareli'),
    UpDistrict(hindiName: 'सीतापुर', englishName: 'Sitapur'),
    UpDistrict(hindiName: 'उन्नाव', englishName: 'Unnao'),
    UpDistrict(hindiName: 'हरदोई', englishName: 'Hardoi'),
    UpDistrict(hindiName: 'बाराबंकी', englishName: 'Barabanki'),
    UpDistrict(hindiName: 'लखीमपुर खीरी', englishName: 'Kheri / Lakhimpur'),
    UpDistrict(hindiName: 'अम्बेडकर नगर', englishName: 'Ambedkar Nagar'),
    UpDistrict(hindiName: 'अमेठी', englishName: 'Amethi'),
    UpDistrict(hindiName: 'अमरोहा', englishName: 'Amroha'),
    UpDistrict(hindiName: 'औरैया', englishName: 'Auraiya'),
    UpDistrict(hindiName: 'बागपत', englishName: 'Baghpat'),
    UpDistrict(hindiName: 'बहराइच', englishName: 'Bahraich'),
    UpDistrict(hindiName: 'बलिया', englishName: 'Ballia'),
    UpDistrict(hindiName: 'बलरामपुर', englishName: 'Balrampur'),
    UpDistrict(hindiName: 'बांदा', englishName: 'Banda'),
    UpDistrict(hindiName: 'भदोही', englishName: 'Bhadohi'),
    UpDistrict(hindiName: 'बिजनौर', englishName: 'Bijnor'),
    UpDistrict(hindiName: 'बदायूं', englishName: 'Budaun'),
    UpDistrict(hindiName: 'बुलंदशहर', englishName: 'Bulandshahr'),
    UpDistrict(hindiName: 'चंदौली', englishName: 'Chandauli'),
    UpDistrict(hindiName: 'चित्रकूट', englishName: 'Chitrakoot'),
    UpDistrict(hindiName: 'देवरिया', englishName: 'Deoria'),
    UpDistrict(hindiName: 'एटा', englishName: 'Etah'),
    UpDistrict(hindiName: 'इटावा', englishName: 'Etawah'),
    UpDistrict(hindiName: 'फर्रुखाबाद', englishName: 'Farrukhabad'),
    UpDistrict(hindiName: 'फतेहपुर', englishName: 'Fatehpur'),
    UpDistrict(hindiName: 'गाजीपुर', englishName: 'Ghazipur'),
    UpDistrict(hindiName: 'गोंडा', englishName: 'Gonda'),
    UpDistrict(hindiName: 'हमीरपुर', englishName: 'Hamirpur'),
    UpDistrict(hindiName: 'हापुड़', englishName: 'Hapur'),
    UpDistrict(hindiName: 'हाथरस', englishName: 'Hathras'),
    UpDistrict(hindiName: 'जालौन (उरई)', englishName: 'Jalaun'),
    UpDistrict(hindiName: 'जौनपुर', englishName: 'Jaunpur'),
    UpDistrict(hindiName: 'कन्नौज', englishName: 'Kannauj'),
    UpDistrict(hindiName: 'कासगंज', englishName: 'Kasganj'),
    UpDistrict(hindiName: 'कौशाम्बी', englishName: 'Kaushambi'),
    UpDistrict(hindiName: 'कुशीनगर', englishName: 'Kushinagar'),
    UpDistrict(hindiName: 'ललितपुर', englishName: 'Lalitpur'),
    UpDistrict(hindiName: 'महराजगंज', englishName: 'Maharajganj'),
    UpDistrict(hindiName: 'महोबा', englishName: 'Mahoba'),
    UpDistrict(hindiName: 'मैनपुरी', englishName: 'Mainpuri'),
    UpDistrict(hindiName: 'मऊ', englishName: 'Mau'),
    UpDistrict(hindiName: 'पीलीभीत', englishName: 'Pilibhit'),
    UpDistrict(hindiName: 'प्रतापगढ़', englishName: 'Pratapgarh'),
    UpDistrict(hindiName: 'रामपुर', englishName: 'Rampur'),
    UpDistrict(hindiName: 'संभल', englishName: 'Sambhal'),
    UpDistrict(hindiName: 'संत कबीर नगर', englishName: 'Sant Kabir Nagar'),
    UpDistrict(hindiName: 'शामली', englishName: 'Shamli'),
    UpDistrict(hindiName: 'श्रावस्ती', englishName: 'Shravasti'),
    UpDistrict(hindiName: 'सिद्धार्थनगर', englishName: 'Siddharthnagar'),
    UpDistrict(hindiName: 'सोनभद्र', englishName: 'Sonbhadra'),
  ];

  static List<String> getCourtDesignationsForDistrict(String districtName) {
    final cleanDistrict = districtName.trim().isEmpty ? 'लखनऊ' : districtName.trim();
    return [
      'CJM (मुख्य न्यायिक मजिस्ट्रेट, $cleanDistrict)',
      'ACJM-I (अपर मुख्य न्यायिक मजिस्ट्रेट-I, $cleanDistrict)',
      'ACJM-II (अपर मुख्य न्यायिक मजिस्ट्रेट-II, $cleanDistrict)',
      'JMFC (न्यायिक मजिस्ट्रेट प्रथम श्रेणी, $cleanDistrict)',
      'जिला एवं सत्र न्यायालय (District & Sessions Court, $cleanDistrict)',
      'अपर जिला एवं सत्र न्यायाधीश (ADJ Court, $cleanDistrict)',
      'विशेष सत्र न्यायाधीश (पॉक्सो / SC-ST कोर्ट, $cleanDistrict)',
      'विशेष एनडीपीएस न्यायालय (NDPS Court, $cleanDistrict)',
      'विशेष न्यायालय (गैंगस्टर्स एक्ट, $cleanDistrict)',
      'न्यायालय सिविल जज (जू.डि.) / न्यायिक मजिस्ट्रेट, $cleanDistrict',
    ];
  }
}
